### ISSUE TITLE
Question about the pretrained model.

### ISSUE THREAD

**Issue by Frank-Dz** [facebookresearch/xR-EgoPose#11]
If it is possible to release the pre-trained model?
Especially the one, you trained on H36M+COCO?

Thank you very much!

**Comment by Frank-Dz** [comment]
Another question is, this paper is extended to a journal paper in which you also predict a rotation of joints.
Seems like it is not contained in this repo. The only rotation is the annotation in the dataset. Or am I missing sth? 

Thank you very much!

**Comment by DenisTome** [comment]
Hi, yes this paper has been extended in https://ieeexplore.ieee.org/abstract/document/9217955
The json file contains the 'rot' field for each joint. E.g.
```
"joints": [
    {
      "name": "mixamorig:Head",
      "rot": [
        0.1195067877059552,
        0.40917683134860916,
        -0.106976547196741
      ],
      "trans": [
        0.9783344864845276,
        147.03970336914065,
        -4.640457630157471
      ]
    }
```
All the information needed is already contained in there.
Regarding the pre-trained models, I do not have anymore access to them.

**Comment by Frank-Dz** [comment]
> Hi, yes this paper has been extended in https://ieeexplore.ieee.org/abstract/document/9217955
> The json file contains the 'rot' field for each joint. E.g.
> 
> ```
> "joints": [
>     {
>       "name": "mixamorig:Head",
>       "rot": [
>         0.1195067877059552,
>         0.40917683134860916,
>         -0.106976547196741
>       ],
>       "trans": [
>         0.9783344864845276,
>         147.03970336914065,
>         -4.640457630157471
>       ]
>     }
> ```
> 
> All the information needed is already contained in there.
> Regarding the pre-trained models, I do not have anymore access to them.

Thank you for your reply. 
May I know the running time of the method in the journal paper (the FPS)?

Thank you very much!

**Comment by DenisTome** [comment]
I don't remember the runtime but I believe it was around 3/4 fps
