### ISSUE TITLE
question about pts3d_fisheye

### ISSUE THREAD

**Issue by vhehduatks** [facebookresearch/xR-EgoPose#22]
i try to recovery 3d pose
![image](https://user-images.githubusercontent.com/64114699/200486973-164abb0a-d74c-47e4-88ec-59feb2549708.png)
by using "pts3d_fisheye" in "female_001_a_a_000001.json"
and this is my code
```python
temp_3d_coords=temp_json['pts3d_fisheye']
x=temp_3d_coords[0]
y=temp_3d_coords[1]
z=temp_3d_coords[2]
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(x,y,z,marker='o',s=15)

for i,(x,y,z) in enumerate(zip(x,y,z)):
    ax.text(x,y,z,str(i))

ax.legend()
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()
```
i wondering why 3d figure not look like that compared to
![image](https://user-images.githubusercontent.com/64114699/200487665-3cbf2d76-4476-4cb3-9fd1-7301a7d7d04f.png)
and this
![image](https://user-images.githubusercontent.com/64114699/200739010-8909f5d3-aa39-4e20-9b61-bf9aef5d2b7a.png)

**Comment by DenisTome** [comment]
The scale of the axes on your plot is not the same...

**Comment by vhehduatks** [comment]
![image](https://user-images.githubusercontent.com/64114699/201246600-27067b91-c2cf-4cc8-8572-c87176996e19.png)
holy... 
thank you for answering the stupid question
