### ISSUE TITLE
Results on Human3.6M

### ISSUE THREAD

**Issue by zhangyahu1** [facebookresearch/xR-EgoPose#8]
Thanks for sharing your great work!
I  notice that your proposd method is also evaluated on Human 3.6M dataset. Do you use the subjects of four camera views to train and test your model or only using front-views subject?

**Comment by DenisTome** [comment]
Hi,
thanks. We do use all camera views, not only the frontal one.
The validation protocol used to generate the results is the same as used by other papers for standard comparison.
